# Generated by Django 3.0.2 on 2020-05-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('academic_position', models.CharField(max_length=100)),
                ('management_position', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=500)),
                ('works', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
