# Generated by Django 3.0.2 on 2020-05-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_auto_20200502_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
