# Generated by Django 3.0.2 on 2020-05-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_auto_20200510_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
