# Generated by Django 3.0.2 on 2020-05-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0004_teacher_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
