# Generated by Django 3.0.2 on 2020-05-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0008_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='education_position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
