# Generated by Django 3.0.2 on 2020-05-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0009_auto_20200526_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='academic_position',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='education_position',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
