# Generated by Django 3.0.2 on 2020-05-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0011_auto_20200528_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='academic_position',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='education_position',
            field=models.CharField(default='', max_length=20),
        ),
    ]
