# Generated by Django 3.0.2 on 2020-05-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0012_auto_20200530_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='academic_position',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='education_position',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
