# Generated by Django 3.0.2 on 2020-05-02 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrance_Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('gat', models.FloatField()),
                ('pat1', models.FloatField()),
                ('pat2', models.FloatField()),
                ('onet', models.FloatField()),
                ('gpax', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50)),
                ('grade_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100, null=True)),
                ('mother', models.CharField(max_length=50)),
                ('mother_phone', models.CharField(max_length=10, null=True)),
                ('mother_income', models.FloatField(null=True)),
                ('father', models.CharField(max_length=50, null=True)),
                ('father_phone', models.CharField(max_length=10, null=True)),
                ('father_income', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('curri', models.IntegerField()),
                ('major_track', models.CharField(max_length=20)),
                ('gpa', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('line_id', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Parent')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entrance_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_school_curriculum', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('educaeted_year', models.IntegerField(null=True)),
                ('TCAS', models.IntegerField()),
                ('entrance_score', models.FloatField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Entrance_Score')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Grade')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Student')),
            ],
        ),
    ]
