# Generated by Django 3.0.2 on 2020-05-11 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20200511_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stitile', to='Student.Title'),
        ),
    ]
