# Generated by Django 3.0.2 on 2020-05-11 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_auto_20200511_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='titles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stitile', to='Student.Title'),
        ),
    ]
