# Generated by Django 3.0.2 on 2020-05-11 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_parent_ftitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='mtitle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mtitle', to='Student.Title'),
        ),
    ]
