# Generated by Django 3.0.2 on 2020-05-11 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_auto_20200509_1646'),
        ('Student', '0009_parent_mtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='curri',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stitile', to='Course.Curriculum'),
        ),
    ]
