# Generated by Django 3.0.2 on 2020-05-11 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_auto_20200511_1000'),
        ('Student', '0011_remove_parent_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='curri',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Course.Curriculum'),
        ),
        migrations.AlterField(
            model_name='student',
            name='titles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Student.Title'),
        ),
    ]
