# Generated by Django 3.0.2 on 2020-05-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_auto_20200511_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
