# Generated by Django 3.0.2 on 2020-05-23 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0014_auto_20200523_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ent_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.Entrance_Info'),
        ),
        migrations.AlterField(
            model_name='entrance_info',
            name='school',
            field=models.CharField(max_length=200),
        ),
    ]
