# Generated by Django 3.0.2 on 2020-05-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0015_auto_20200523_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='father_income',
            new_name='P_income',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='father_phone',
            new_name='P_phone',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='father',
            new_name='p_name',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='fsurname',
            new_name='p_surname',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='ftitle',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='mother_income',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='mother_phone',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='msurname',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='mtitle',
        ),
        migrations.AddField(
            model_name='parent',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Student.Title'),
        ),
    ]
