# Generated by Django 3.0.2 on 2020-05-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0016_auto_20200525_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
