# Generated by Django 3.0.2 on 2020-05-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0017_student_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='campus',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
