# Generated by Django 3.0.2 on 2020-05-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0018_student_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrance_info',
            name='province',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
