# Generated by Django 3.0.2 on 2020-05-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0019_entrance_info_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
