# Generated by Django 3.0.2 on 2020-05-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0020_auto_20200525_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
