# Generated by Django 3.0.2 on 2020-05-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0021_auto_20200525_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='p_relation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='P_phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
