# Generated by Django 3.0.2 on 2020-05-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0023_auto_20200525_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='P_income',
            new_name='p_income',
        ),
    ]
