# Generated by Django 3.0.2 on 2020-05-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0024_auto_20200525_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admitc_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='applicant_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='academic_year',
            field=models.IntegerField(),
        ),
    ]
