# Generated by Django 3.0.2 on 2020-05-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0025_auto_20200526_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='applicant_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
