# Generated by Django 3.0.2 on 2020-05-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0026_student_applicant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='academic_year',
            field=models.IntegerField(null=True),
        ),
    ]
