# Generated by Django 3.0.2 on 2020-05-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0028_auto_20200526_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admitc_year',
            new_name='admit_year',
        ),
    ]
