# Generated by Django 3.0.2 on 2020-05-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0031_auto_20200526_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrance_info',
            name='TCAS',
        ),
        migrations.AddField(
            model_name='student',
            name='tcas',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
