# Generated by Django 3.0.2 on 2020-05-28 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0032_auto_20200528_0516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
