# Generated by Django 3.0.2 on 2020-05-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0033_delete_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
