# Generated by Django 3.0.2 on 2020-05-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0034_auto_20200528_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='campus',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='line_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='major_track',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
