# Generated by Django 3.0.2 on 2020-05-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0035_auto_20200528_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
