# Generated by Django 3.0.2 on 2020-05-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0036_auto_20200528_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrance_info',
            old_name='high_school_curriculum',
            new_name='high_school_plan',
        ),
    ]
