# Generated by Django 3.0.2 on 2020-05-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0037_auto_20200528_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrance_info',
            name='high_school_plan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrance_info',
            name='school',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
