# Generated by Django 3.0.2 on 2020-05-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0039_auto_20200528_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='titles',
            field=models.CharField(default='', max_length=200),
        ),
    ]
