# Generated by Django 3.0.2 on 2020-05-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0040_auto_20200530_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major_track',
            field=models.CharField(default='', max_length=100),
        ),
    ]
