# Generated by Django 3.0.2 on 2020-05-31 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0041_auto_20200530_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_for_lastest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_for_cs101', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check101', to='Student.Enrollment')),
                ('check_for_cs223', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check223', to='Student.Enrollment')),
                ('check_for_cs300', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check300', to='Student.Enrollment')),
            ],
        ),
    ]
