# Generated by Django 3.0.2 on 2020-05-31 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0042_check_for_lastest'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_for_lastest',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.Student'),
        ),
    ]
