# Generated by Django 3.0.2 on 2020-05-31 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0043_check_for_lastest_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_for_lastest',
            name='check_for_cs101',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check101', to='Student.Enrollment'),
        ),
        migrations.AlterField(
            model_name='check_for_lastest',
            name='check_for_cs223',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check223', to='Student.Enrollment'),
        ),
        migrations.AlterField(
            model_name='check_for_lastest',
            name='check_for_cs300',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check300', to='Student.Enrollment'),
        ),
    ]
