# Generated by Django 3.0.2 on 2020-05-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0045_auto_20200531_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='course_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course_id',
            field=models.CharField(max_length=20),
        ),
    ]
