# Generated by Django 3.0.2 on 2020-06-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0046_auto_20200531_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='credit',
            field=models.IntegerField(null=True),
        ),
    ]
