# Generated by Django 3.0.2 on 2020-06-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0048_auto_20200604_0745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check_for_lastest',
        ),
    ]
