# Generated by Django 3.0.2 on 2020-05-02 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20)),
                ('curriculum', models.IntegerField()),
                ('course_name', models.CharField(max_length=50, null=True)),
                ('course_description', models.CharField(max_length=1000, null=True)),
                ('credit', models.IntegerField(null=True)),
                ('lecture_hours', models.IntegerField(null=True)),
                ('lab_hours', models.IntegerField(null=True)),
                ('selfstudy_hours', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='course_condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='course_sector_curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.IntegerField(null=True)),
                ('sector_no', models.IntegerField()),
                ('sector_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='course_sector_tgf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.IntegerField(null=True)),
                ('tqf_sector_no', models.IntegerField(null=True)),
                ('tqf_sector_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='major_or_track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.CharField(max_length=20, null=True)),
                ('major_or_track', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='usage_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(max_length=20)),
                ('usage_condition', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereq_set', to='Course.Course')),
                ('pre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postreq_set', to='Course.Course')),
                ('pre_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Course.Prerequisite_Type')),
            ],
        ),
        migrations.CreateModel(
            name='course_usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comdition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.course_condition')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Course')),
                ('course_sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.course_sector_curriculum')),
                ('course_tqf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.course_sector_tgf')),
                ('elective_or_mandatory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.usage_type')),
                ('major_or_track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.major_or_track')),
            ],
        ),
    ]
