# Generated by Django 3.0.2 on 2020-05-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='major_or_track',
            name='m_or_t',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='major_or_track',
            name='major_or_track',
            field=models.CharField(max_length=100),
        ),
    ]
