# Generated by Django 3.0.2 on 2020-05-11 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_auto_20200509_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_sector_curriculum',
            name='curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.Curriculum'),
        ),
        migrations.AlterField(
            model_name='course_sector_tgf',
            name='curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.Curriculum'),
        ),
        migrations.AlterField(
            model_name='major_or_track',
            name='curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.Curriculum'),
        ),
    ]
