# Generated by Django 3.0.2 on 2020-05-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_auto_20200511_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_sector_curriculum',
            name='sector_no',
            field=models.IntegerField(null=True),
        ),
    ]
