# Generated by Django 3.0.2 on 2020-05-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0007_auto_20200523_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='curri',
            field=models.IntegerField(),
        ),
    ]
