# Generated by Django 3.0.2 on 2020-05-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0010_remove_course_usage_course_tqf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_usage',
            old_name='comdition',
            new_name='condition',
        ),
    ]
