# Generated by Django 3.0.2 on 2020-05-28 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0012_auto_20200527_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prerequisite',
            old_name='post',
            new_name='post_course',
        ),
        migrations.RenameField(
            model_name='prerequisite',
            old_name='pre',
            new_name='pre_course',
        ),
        migrations.AddField(
            model_name='course_usage',
            name='course_tqf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.course_sector_tgf'),
        ),
    ]
