# Generated by Django 3.0.2 on 2020-05-28 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0013_auto_20200528_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_sector_curriculum',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='course_sector_tgf',
            name='curriculum',
        ),
    ]
