# Generated by Django 3.0.2 on 2020-05-28 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0015_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_usage',
            name='condition',
        ),
        migrations.DeleteModel(
            name='course_condition',
        ),
    ]
