# Generated by Django 3.0.2 on 2020-05-30 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0020_course_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_usage',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.course_condition'),
        ),
    ]
