# Generated by Django 3.0.2 on 2020-05-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0021_course_usage_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisite',
            name='group',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='post_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prereq_set', to='Course.Course'),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='pre_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postreq_set', to='Course.Course'),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='pre_type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.Prerequisite_Type'),
        ),
    ]
